url: https://superliminal-defenestration.github.io/
baseurl: ''

title: SuperDef
email: superliminaldefenestration@gmail.com
description: "Website for Superliminal Defenestration's projects and accomplishments to be put on display."


people:
- name: Nathan
  pic: 1
  position: Lead Designer / Creator
  social:
    - title: discord
      url: suop#6295
    - title: github
      url: https://github.com/Pengalu

- name: Henry
  pic: 2
  position: Moral Support
  social:
    - title: discord
      url: hue#2552
    - title: github
      url: https://github.com/hueblu

social:
  - title: discord
    url: suop#6295
  - title: github
    url: https://github.com/Superliminal-Defenestration

# address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

markdown: kramdown
permalink: pretty